# Generated by Django 6.0.5 on 2026-05-09 11:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_weight', models.IntegerField(help_text='Total maximum weight of all symptoms for this disease')),
                ('confidence_threshold', models.DecimalField(decimal_places=2, help_text='Threshold percentage (e.g., 35.00 for 35%)', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, help_text='Optional User ID for anonymous consultations', null=True)),
                ('highest_confidence', models.DecimalField(blank=True, decimal_places=2, help_text='Highest confidence score obtained', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result_disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.disease')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.IntegerField(help_text='Weight of the symptom for this disease (1-10)')),
                ('type', models.CharField(choices=[('utama', 'Utama'), ('pendukung', 'Pendukung'), ('ringan', 'Ringan')], default='utama', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='api.disease')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_rules', to='api.symptom')),
            ],
            options={
                'unique_together': {('disease', 'symptom')},
            },
        ),
        migrations.CreateModel(
            name='ConsultationSymptom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms_selected', to='api.consultation')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.symptom')),
            ],
            options={
                'unique_together': {('consultation', 'symptom')},
            },
        ),
    ]
